### ISSUE TITLE
Migrate to Netty

### ISSUE THREAD

**Issue by MrPowerGamerBR** [PocketDreams/SequinLand#11]
Nukkit still uses a combo of Netty + Java sockets, why not migrate to 100% Netty?

**Comment by MarfGamer** [comment]
I see this issue is open when you are trying to use JRakNet, is this Netty + Java socket stuff meant for MCPE connections or other stuff?

**Comment by MrPowerGamerBR** [comment]
I created this issue before I did know about JRakNet (I think?), but now
that JRakNet is implemented (and JRakNet uses Netty) there isn't too many
reasons to keep this open... Will close this ASAP.

Em 20 de fev de 2017 23:57, "Trent" <notifications@github.com> escreveu:

**Comment by MrPowerGamerBR** [comment]
Now that SequinLand uses JRakNet by @MarfGamer, this issue is now obsolete since JRakNet uses Netty, so... 🤷‍♂️
