### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by NycuRO** [PocketDreams/SequinLand#15]
Hi. I can improve generator in this software ?:)

**Comment by MrPowerGamerBR** [comment]
@NycuRO as long as it is not a buggy implementation, then yes.

But since SequinLand is a Nukkit fork, you can push your generator changes to the Nukkit repo (since I push the changes from Nukkit's master branch too)

**Comment by NycuRO** [comment]
Yes but is my generator and Creeper ,i like to improve...

For example ,generation is buggy. Need change temperatures and rainfall ( I know is correct ) because is generate again again and again swamp. @MrPowerGamerBR
