### ISSUE TITLE
Add Transfer API

### ISSUE THREAD

**Issue by MrPowerGamerBR** [PocketDreams/SequinLand#2]
```Player#transfer(String ip, int port);```

**Comment by MrPowerGamerBR** [comment]
MCPE 1.0.3.0 is now relased, so I think I can implement this API now...

**Comment by thebigsmileXD** [comment]
Officially? Havent got the update, only beta

**Comment by MrPowerGamerBR** [comment]
@thebigsmileXD yes
![http://i.imgur.com/ULdAsCr.png](http://i.imgur.com/ULdAsCr.png)

**Comment by thebigsmileXD** [comment]
https://minecraft.net/en-us/article/candy-pack-sweetens-pocket-win-10 whooops
