### ISSUE TITLE
TextFormat does not reset formatting when a new colour is applied.

### ISSUE THREAD

**Issue by L3W3S** [PocketDreams/SequinLand#28]
### Issue description
When colourising a message using TextFormat#colorise(String message), formatting is not set back to default when a colour is applied. This may or may not be a feature, but in Minecraft PC this is the case.

### Steps to reproduce the issue
For example, this should outline the issue:

> "&a&lThis is green and bold and this is correct."
> "&l&cThis is red and bold, but it shouldn't be. It should just be red with no formatting."

### OS and versions
* Nukkit Version: 1.0-dev
* Java Version: 1.8.0_111
* Host OS: Windows
* Client Edition: Windows 10
* Client Version: 1.0.3

**Comment by MrPowerGamerBR** [comment]
That's a MCPE issue, in PC the formatting is reset when you use another color, while in MCPE it isn't.

You need to use the resetting code (&r)

**Comment by L3W3S** [comment]
Can't this be applied directly into Nukkit by applying &r before a colour?

**Comment by MrPowerGamerBR** [comment]
@L3W3S it is possible? Yeah, but that will break plugins (not really "break", they would just display something that wasn't expected to) that are relying on the old "changing colors doesn't remove the format" style. I may add a argument to TextFormat to "reset on color change" tho

**Comment by L3W3S** [comment]
@MrPowerGamerBR That sounds like a great idea. I have a suggestion, for plugins that wish to reset the changing colours, perhaps a setting can be applied to TextFormat on enable.

`TextFormat.setResetColors(boolean)`

For servers which use public plugins this may be annoying if you just want to apply it to a single plugin. However my server is entirely custom and going through every message sending to append a parameter can be time consuming.

**Comment by MrPowerGamerBR** [comment]
Adding the new method...
